import { z } from "zod";

export const newspaperSchema = z.object({
  id: z.string(),
  name: z.string(),
  logo: z.string(),
  epaperUrl: z.string(),
  language: z.string(),
  region: z.string(),
  featured: z.boolean().optional(),
});

export type Newspaper = z.infer<typeof newspaperSchema>;

export const languageSchema = z.object({
  code: z.string(),
  name: z.string(),
  nativeName: z.string(),
});

export type Language = z.infer<typeof languageSchema>;

export const languages: Language[] = [
  { code: "all", name: "All", nativeName: "All" },
  { code: "english", name: "English", nativeName: "English" },
  { code: "hindi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "marathi", name: "Marathi", nativeName: "मराठी" },
  { code: "gujarati", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "tamil", name: "Tamil", nativeName: "தமிழ்" },
  { code: "telugu", name: "Telugu", nativeName: "తెలుగు" },
  { code: "bengali", name: "Bengali", nativeName: "বাংলা" },
  { code: "kannada", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "malayalam", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "punjabi", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
];

export const newspapers: Newspaper[] = [
  // English Newspapers
  {
    id: "toi",
    name: "Times of India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/The_Times_of_India_Logo.svg/320px-The_Times_of_India_Logo.svg.png",
    epaperUrl: "https://epaper.timesgroup.com/",
    language: "english",
    region: "National",
    featured: true,
  },
  {
    id: "hindu",
    name: "The Hindu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/The_Hindu_Logo.svg/320px-The_Hindu_Logo.svg.png",
    epaperUrl: "https://epaper.thehindu.com/",
    language: "english",
    region: "National",
    featured: true,
  },
  {
    id: "ht",
    name: "Hindustan Times",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Hindustan_Times_logo.svg/320px-Hindustan_Times_logo.svg.png",
    epaperUrl: "https://epaper.hindustantimes.com/",
    language: "english",
    region: "National",
    featured: true,
  },
  {
    id: "ie",
    name: "Indian Express",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Indian_Express_logo.svg/320px-Indian_Express_logo.svg.png",
    epaperUrl: "https://indianexpress.com/todays-paper/",
    language: "english",
    region: "National",
  },
  {
    id: "deccan",
    name: "Deccan Chronicle",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Deccan-chronicle.svg/320px-Deccan-chronicle.svg.png",
    epaperUrl: "https://epaper.deccanchronicle.com/",
    language: "english",
    region: "South",
  },
  {
    id: "telegraph",
    name: "The Telegraph",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Telegraph_%28Kolkata%29_logo.svg/320px-The_Telegraph_%28Kolkata%29_logo.svg.png",
    epaperUrl: "https://epaper.telegraphindia.com/",
    language: "english",
    region: "East",
  },
  // Hindi Newspapers
  {
    id: "dainik-jagran",
    name: "Dainik Jagran",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Dainik_Jagran_logo.svg/320px-Dainik_Jagran_logo.svg.png",
    epaperUrl: "https://epaper.jagran.com/",
    language: "hindi",
    region: "National",
    featured: true,
  },
  {
    id: "dainik-bhaskar",
    name: "Dainik Bhaskar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Dainik_Bhaskar_logo.svg/320px-Dainik_Bhaskar_logo.svg.png",
    epaperUrl: "https://epaper.bhaskar.com/",
    language: "hindi",
    region: "National",
    featured: true,
  },
  {
    id: "amar-ujala",
    name: "Amar Ujala",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Amar_Ujala_Logo.svg/320px-Amar_Ujala_Logo.svg.png",
    epaperUrl: "https://epaper.amarujala.com/",
    language: "hindi",
    region: "North",
  },
  {
    id: "hindustan",
    name: "Hindustan",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Hindustan_hindi_logo.svg/320px-Hindustan_hindi_logo.svg.png",
    epaperUrl: "https://epaper.livehindustan.com/",
    language: "hindi",
    region: "National",
  },
  {
    id: "navbharat",
    name: "Navbharat Times",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Navbharat_Times_logo.svg/320px-Navbharat_Times_logo.svg.png",
    epaperUrl: "https://navbharattimes.indiatimes.com/",
    language: "hindi",
    region: "National",
  },
  {
    id: "rajasthan-patrika",
    name: "Rajasthan Patrika",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Rajasthan_Patrika_Logo.svg/320px-Rajasthan_Patrika_Logo.svg.png",
    epaperUrl: "https://epaper.patrika.com/",
    language: "hindi",
    region: "West",
  },
  // Marathi Newspapers
  {
    id: "lokmat",
    name: "Lokmat",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Lokmat_logo.svg/320px-Lokmat_logo.svg.png",
    epaperUrl: "https://epaper.lokmat.com/",
    language: "marathi",
    region: "Maharashtra",
    featured: true,
  },
  {
    id: "loksatta",
    name: "Loksatta",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Loksatta_logo.svg/320px-Loksatta_logo.svg.png",
    epaperUrl: "https://epaper.loksatta.com/",
    language: "marathi",
    region: "Maharashtra",
  },
  {
    id: "sakal",
    name: "Sakal",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Sakal_Newspaper_Logo.svg/320px-Sakal_Newspaper_Logo.svg.png",
    epaperUrl: "https://epaper.esakal.com/",
    language: "marathi",
    region: "Maharashtra",
  },
  {
    id: "maharashtra-times",
    name: "Maharashtra Times",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Maharashtra_Times_logo.svg/320px-Maharashtra_Times_logo.svg.png",
    epaperUrl: "https://maharashtratimes.com/",
    language: "marathi",
    region: "Maharashtra",
  },
  {
    id: "pudhari",
    name: "Pudhari",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Pudhari_logo.svg/320px-Pudhari_logo.svg.png",
    epaperUrl: "https://epaper.pudhari.com/",
    language: "marathi",
    region: "Maharashtra",
  },
  // Gujarati Newspapers
  {
    id: "divya-bhaskar",
    name: "Divya Bhaskar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Divya_Bhaskar_logo.svg/320px-Divya_Bhaskar_logo.svg.png",
    epaperUrl: "https://epaper.divyabhaskar.co.in/",
    language: "gujarati",
    region: "Gujarat",
  },
  {
    id: "gujarat-samachar",
    name: "Gujarat Samachar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Gujarat_Samachar_logo.svg/320px-Gujarat_Samachar_logo.svg.png",
    epaperUrl: "https://epaper.gujaratsamachar.com/",
    language: "gujarati",
    region: "Gujarat",
  },
  {
    id: "sandesh",
    name: "Sandesh",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sandesh_Logo.svg/320px-Sandesh_Logo.svg.png",
    epaperUrl: "https://epaper.sandesh.com/",
    language: "gujarati",
    region: "Gujarat",
  },
  // Tamil Newspapers
  {
    id: "dinamalar",
    name: "Dinamalar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Dinamalar_logo.svg/320px-Dinamalar_logo.svg.png",
    epaperUrl: "https://epaper.dinamalar.com/",
    language: "tamil",
    region: "Tamil Nadu",
  },
  {
    id: "dinamani",
    name: "Dinamani",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Dinamani_logo.svg/320px-Dinamani_logo.svg.png",
    epaperUrl: "https://epaper.dinamani.com/",
    language: "tamil",
    region: "Tamil Nadu",
  },
  {
    id: "daily-thanthi",
    name: "Daily Thanthi",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Daily_Thanthi_logo.svg/320px-Daily_Thanthi_logo.svg.png",
    epaperUrl: "https://epaper.dailythanthi.com/",
    language: "tamil",
    region: "Tamil Nadu",
  },
  // Telugu Newspapers
  {
    id: "eenadu",
    name: "Eenadu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Eenadu_logo.svg/320px-Eenadu_logo.svg.png",
    epaperUrl: "https://epaper.eenadu.net/",
    language: "telugu",
    region: "Andhra Pradesh",
  },
  {
    id: "sakshi",
    name: "Sakshi",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Sakshi_logo.svg/320px-Sakshi_logo.svg.png",
    epaperUrl: "https://epaper.sakshi.com/",
    language: "telugu",
    region: "Telangana",
  },
  {
    id: "andhra-jyothy",
    name: "Andhra Jyothy",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Andhra_Jyothy_logo.svg/320px-Andhra_Jyothy_logo.svg.png",
    epaperUrl: "https://epaper.andhrajyothy.com/",
    language: "telugu",
    region: "Andhra Pradesh",
  },
  // Bengali Newspapers
  {
    id: "anandabazar",
    name: "Anandabazar Patrika",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Anandabazar_Patrika_logo.svg/320px-Anandabazar_Patrika_logo.svg.png",
    epaperUrl: "https://epaper.anandabazar.com/",
    language: "bengali",
    region: "West Bengal",
  },
  {
    id: "bartaman",
    name: "Bartaman",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Bartaman_Patrika_logo.svg/320px-Bartaman_Patrika_logo.svg.png",
    epaperUrl: "https://epaper.bartamanpatrika.com/",
    language: "bengali",
    region: "West Bengal",
  },
  {
    id: "sangbad-pratidin",
    name: "Sangbad Pratidin",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Sangbad_Pratidin_logo.svg/320px-Sangbad_Pratidin_logo.svg.png",
    epaperUrl: "https://epaper.sangbadpratidin.in/",
    language: "bengali",
    region: "West Bengal",
  },
  // Kannada Newspapers
  {
    id: "prajavani",
    name: "Prajavani",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Prajavani_logo.svg/320px-Prajavani_logo.svg.png",
    epaperUrl: "https://epaper.prajavani.net/",
    language: "kannada",
    region: "Karnataka",
  },
  {
    id: "vijaya-karnataka",
    name: "Vijaya Karnataka",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Vijaya_Karnataka_logo.svg/320px-Vijaya_Karnataka_logo.svg.png",
    epaperUrl: "https://epaper.vijaykarnataka.com/",
    language: "kannada",
    region: "Karnataka",
  },
  {
    id: "udayavani",
    name: "Udayavani",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Udayavani_logo.svg/320px-Udayavani_logo.svg.png",
    epaperUrl: "https://epaper.udayavani.com/",
    language: "kannada",
    region: "Karnataka",
  },
  // Malayalam Newspapers
  {
    id: "malayala-manorama",
    name: "Malayala Manorama",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Malayala_Manorama_logo.svg/320px-Malayala_Manorama_logo.svg.png",
    epaperUrl: "https://epaper.manoramaonline.com/",
    language: "malayalam",
    region: "Kerala",
  },
  {
    id: "mathrubhumi",
    name: "Mathrubhumi",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Mathrubhumi_logo.svg/320px-Mathrubhumi_logo.svg.png",
    epaperUrl: "https://epaper.mathrubhumi.com/",
    language: "malayalam",
    region: "Kerala",
  },
  {
    id: "madhyamam",
    name: "Madhyamam",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Madhyamam_logo.svg/320px-Madhyamam_logo.svg.png",
    epaperUrl: "https://epaper.madhyamam.com/",
    language: "malayalam",
    region: "Kerala",
  },
  // Punjabi Newspapers
  {
    id: "ajit",
    name: "Ajit",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Ajit_Daily_logo.svg/320px-Ajit_Daily_logo.svg.png",
    epaperUrl: "https://epaper.ajitjalandhar.com/",
    language: "punjabi",
    region: "Punjab",
  },
  {
    id: "jagbani",
    name: "Jagbani",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Jagbani_logo.svg/320px-Jagbani_logo.svg.png",
    epaperUrl: "https://epaper.jagbani.com/",
    language: "punjabi",
    region: "Punjab",
  },
];

// User type for future features
export const users = {
  id: "",
  username: "",
  password: "",
};

export type User = typeof users;
export type InsertUser = Omit<User, "id">;
